# Generated by Django 2.1.4 on 2018-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_url', models.CharField(max_length=40)),
                ('ip_prefix', models.CharField(max_length=40)),
                ('as_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=20)),
                ('record_type', models.CharField(max_length=5)),
                ('keyword', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('as_number', models.CharField(max_length=10)),
                ('ip_prefix', models.CharField(max_length=40)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
