# Generated by Django 2.1.4 on 2018-12-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='prefix_url',
            field=models.CharField(max_length=255),
        ),
    ]
