# Generated by Django 2.1.4 on 2018-12-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20181218_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
