# Generated by Django 2.1.4 on 2018-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_asn_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.TextField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
