# Generated by Django 2.1.4 on 2018-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_asn_crawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
