# Generated by Django 2.1.4 on 2018-12-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20181224_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='illegal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='match_ip',
            field=models.BooleanField(default=False),
        ),
    ]
