# Generated by Django 2.1.4 on 2018-12-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20181225_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-ip_prefix']},
        ),
    ]
