# Generated by Django 2.1.4 on 2019-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20181225_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='ip',
            field=models.CharField(max_length=40),
        ),
    ]
